/* ==================================================================
   AmaiCraft - RecipeCraft
   Data comes from data/recipes.json, generated by tools/build.mjs
   straight from the vanilla Minecraft datapack.
   ================================================================== */

'use strict';

const DATA_URL = 'data/recipes.json';
const PAGE = 240;           // cells rendered per batch
const CYCLE_MS = 1100;      // how fast a "any of these" slot cycles

const STATIONS = {
  craft:        { name: 'Crafting Table', icon: 'crafting_table' },
  smelting:     { name: 'Furnace',        icon: 'furnace' },
  blasting:     { name: 'Blast Furnace',  icon: 'blast_furnace' },
  smoking:      { name: 'Smoker',         icon: 'smoker' },
  campfire:     { name: 'Campfire',       icon: 'campfire' },
  stonecutting: { name: 'Stonecutter',    icon: 'stonecutter' },
  smithing:     { name: 'Smithing Table', icon: 'smithing_table' },
  trim:         { name: 'Armor Trim',     icon: 'smithing_table' },
  brewing:      { name: 'Brewing Stand',  icon: 'brewing_stand' },
};
const STATION_ORDER = Object.keys(STATIONS);

let DB = null;
const byResult = new Map();      // item id -> [recipe]
const byIngredient = new Map();  // item id -> Set(result id)

/* ---------- tiny helpers ------------------------------------------- */

const $ = (sel) => document.querySelector(sel);
const el = (tag, cls, html) => {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (html != null) n.innerHTML = html;
  return n;
};
const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const itemName = (id) => (DB.items[id] ? DB.items[id].n : id);
const hasIcon = (id) => DB.items[id] && !DB.items[id].m;
const iconUrl = (id) => `assets/items/${id}.${(DB.items[id] && DB.items[id].x) || 'png'}`;

const ICON_EXTS = ['png', 'webp', 'gif'];

/**
 * The file extension of every icon is recorded at build time. If you swap a
 * texture for another format and forget to re-run tools/build.mjs, the stored
 * one is wrong - so try the other extensions before giving up.
 */
function iconFallback(img) {
  const src = img.getAttribute('src') || '';
  const cur = (/\.(png|webp|gif)$/i.exec(src) || [, ''])[1].toLowerCase();
  const tried = (img.dataset.tried || '') + cur + ',';
  img.dataset.tried = tried;

  const next = ICON_EXTS.find((e) => !tried.includes(e));
  if (next) {
    img.src = src.replace(/\.(png|webp|gif)$/i, '.' + next);
    return;
  }
  const ph = document.createElement('span');
  ph.className = 'ph';
  ph.title = img.alt;
  ph.textContent = '?';
  img.replaceWith(ph);
}

/** <img> for an item, or a "?" placeholder when the texture is not in assets/items */
function iconHTML(id, lazy = true) {
  if (!DB.items[id]) return `<span class="ph" title="${esc(id)}">?</span>`;
  if (!hasIcon(id)) return `<span class="ph" title="${esc(itemName(id))}">?</span>`;
  // .px = raw 16/32 px game sprite: scaled by a whole factor, kept hard-edged
  const cls = DB.items[id].p ? ' class="px"' : '';
  return `<img src="${iconUrl(id)}"${cls} alt="${esc(itemName(id))}"${lazy ? ' loading="lazy"' : ''}` +
         ` decoding="async" onerror="iconFallback(this)">`;
}

/** every ingredient shape -> a flat list of item ids */
const ingItems = (ing) => (ing == null ? [] : typeof ing === 'string' ? [ing] : ing.i || []);

/* ---------- indexes -------------------------------------------------- */

function buildIndexes() {
  for (const r of DB.recipes) {
    if (!byResult.has(r.r)) byResult.set(r.r, []);
    byResult.get(r.r).push(r);

    const inputs = new Set();
    if (r.g) for (const s of r.g) ingItems(s).forEach((i) => inputs.add(i));
    for (const f of ['in', 'base', 'add', 'tpl']) ingItems(r[f]).forEach((i) => inputs.add(i));

    for (const i of inputs) {
      if (i === r.r) continue;
      if (!byIngredient.has(i)) byIngredient.set(i, new Set());
      byIngredient.get(i).add(r.r);
    }
  }
}

/* ---------- state ---------------------------------------------------- */

const state = {
  category: 'all',
  query: '',
  craftableOnly: true,
  list: [],       // ids currently matching
  shown: 0,
  history: [],
};

let searchIndex = [];  // [{ id, name, lower }]

function computeList() {
  const q = state.query.trim().toLowerCase();
  let out;

  if (q) {
    const starts = [], contains = [];
    for (const it of searchIndex) {
      const p = it.lower.indexOf(q);
      if (p === 0) starts.push(it.id);
      else if (p > 0 || it.id.includes(q)) contains.push(it.id);
    }
    out = starts.concat(contains);
  } else {
    out = searchIndex.map((i) => i.id);
  }

  out = out.filter((id) => {
    const it = DB.items[id];
    if (it.h) return false;
    if (state.category !== 'all' && it.c !== state.category) return false;
    if (state.craftableOnly && !byResult.has(id)) return false;
    return true;
  });

  state.list = out;
  state.shown = 0;
}

/* ---------- grid ----------------------------------------------------- */

const gridEl = $('#grid');
let sentinel = null;

function renderGrid(reset = true) {
  hideTip();
  if (reset) {
    gridEl.innerHTML = '';
    state.shown = 0;
  }
  const frag = document.createDocumentFragment();
  const end = Math.min(state.shown + PAGE, state.list.length);

  for (let i = state.shown; i < end; i++) {
    const id = state.list[i];
    const cell = el('div', 'cell' + (byResult.has(id) ? '' : ' no-recipe'));
    cell.dataset.item = id;
    cell.tabIndex = 0;
    cell.setAttribute('role', 'option');
    cell.innerHTML = iconHTML(id);
    // stagger only the first screenful, otherwise it feels sluggish
    if (i - state.shown < 60) cell.style.animationDelay = ((i - state.shown) * 4) + 'ms';
    else cell.style.animation = 'none';
    frag.appendChild(cell);
  }
  state.shown = end;
  gridEl.appendChild(frag);

  $('#grid-count').textContent =
    state.list.length + (state.list.length === 1 ? ' item' : ' items');
  $('#empty').hidden = state.list.length > 0;

  if (sentinel) sentinel.remove();
  if (state.shown < state.list.length) {
    sentinel = el('div', 'sentinel');
    sentinel.style.gridColumn = '1 / -1';
    sentinel.style.height = '1px';
    gridEl.appendChild(sentinel);
    io.observe(sentinel);
  } else {
    sentinel = null;
  }
}

const io = new IntersectionObserver((entries) => {
  for (const e of entries) {
    if (e.isIntersecting) {
      io.unobserve(e.target);
      renderGrid(false);
    }
  }
}, { rootMargin: '400px' });

function refresh() {
  computeList();
  const cat = DB.categories.find((c) => c.id === state.category);
  $('#grid-title').textContent = state.query
    ? `Results for "${state.query}"`
    : cat ? cat.name : 'All items';
  renderGrid(true);
}

/* ---------- tooltip --------------------------------------------------- */

const tip = $('#tooltip');

function showTip(id, x, y) {
  tip.innerHTML = `${esc(itemName(id))}<small>${esc(id)}${byResult.has(id) ? '' : ' · no recipe'}</small>`;
  tip.hidden = false;
  positionTip(x, y);
}
function positionTip(x, y) {
  const w = tip.offsetWidth, h = tip.offsetHeight;
  tip.style.left = Math.min(x, window.innerWidth - w - 20) + 'px';
  tip.style.top = Math.min(y, window.innerHeight - h - 20) + 'px';
}
const hideTip = () => { tip.hidden = true; };

/* ---------- recipe rendering ------------------------------------------ */

function slotHTML(ing, extraClass = '') {
  const list = ingItems(ing);
  if (!list.length) return `<div class="slot empty"></div>`;
  const id = list[0];
  const cycling = list.length > 1;
  return `<div class="slot ${extraClass}${cycling ? ' cycling' : ''}" data-item="${esc(id)}"${
    cycling ? ` data-cycle="${esc(list.join(','))}" data-idx="0"` : ''
  } title="${esc(cycling ? list.map(itemName).join(' / ') : itemName(id))}">${iconHTML(id)}</div>`;
}

function resultHTML(r) {
  return `<div class="slot big" data-item="${esc(r.r)}" title="${esc(itemName(r.r))}">
      ${iconHTML(r.r)}${r.q > 1 ? `<span class="qty">${r.q}</span>` : ''}
    </div>`;
}

/** the grey GUI box, plus its notes underneath (never inside: a long sentence
    would stretch the box across the whole panel) */
function wrapRecipe(inner, r) {
  const notes = [];
  if (r.s) notes.push('Shapeless — the position of the items does not matter.');
  if (r.note) notes.push(r.note);
  return `<div class="recipe-wrap">
      <div class="recipe">${inner}</div>
      ${notes.map((n) => `<p class="recipe-note">${esc(n)}</p>`).join('')}
    </div>`;
}

function recipeHTML(r) {
  if (r.t === 'craft') {
    return wrapRecipe(`
        <div class="grid-3">${r.g.map((s) => slotHTML(s)).join('')}</div>
        <div class="arrow">➜</div>
        ${resultHTML(r)}`, r);
  }

  if (r.t === 'smithing' || r.t === 'trim') {
    return wrapRecipe(`
        <div class="line">${slotHTML(r.tpl)}${slotHTML(r.base)}${slotHTML(r.add)}</div>
        <div class="arrow">➜</div>
        ${resultHTML(r)}`, r);
  }

  if (r.t === 'brewing') {
    return wrapRecipe(`
        <div class="line">${slotHTML(r.add)}<span class="arrow">+</span>${slotHTML(r.in)}</div>
        <div class="arrow">➜</div>
        ${resultHTML(r)}`, r);
  }

  // furnace family + stonecutter
  const fire = ['smelting', 'blasting', 'smoking', 'campfire'].includes(r.t)
    ? `<div class="station-icon"><img src="assets/gui/fire.gif" class="fire" alt="fuel"></div>`
    : `<div class="station-icon">${iconHTML(STATIONS[r.t].icon)}</div>`;

  return wrapRecipe(`
      <div class="line">${slotHTML(r.in)}${fire}</div>
      <div class="arrow">➜</div>
      ${resultHTML(r)}
      ${r.xp ? `<div class="xp">+${r.xp} XP</div>` : ''}`, r);
}

/* ---------- detail panel ----------------------------------------------- */

const detail = $('#detail');
const backdrop = $('#backdrop');

function openItem(id, push = true) {
  if (!DB.items[id]) return;
  if (push) {
    state.history.push(id);
    if (location.hash.slice(1) !== id) history.replaceState(null, '', '#' + id);
  }

  const it = DB.items[id];
  const cat = DB.categories.find((c) => c.id === it.c);
  const recipes = byResult.get(id) || [];

  let html = `<div class="item-head">
      ${iconHTML(id, false)}
      <div>
        <h2>${esc(it.n)}</h2>
        <div class="meta"><b>${esc(cat ? cat.name : it.c)}</b> · ${esc(id)}</div>
      </div>
    </div>`;

  if (recipes.length) {
    for (const t of STATION_ORDER) {
      const group = recipes.filter((r) => r.t === t);
      if (!group.length) continue;
      html += `<section class="station">
          <h3 class="station-title">${iconHTML(STATIONS[t].icon)}${esc(STATIONS[t].name)}
            ${group.length > 1 ? `<span class="count">${group.length} ways</span>` : ''}
          </h3>
          ${group.map(recipeHTML).join('')}
        </section>`;
    }
  } else {
    html += `<div class="no-recipe-box">
        <strong>No recipe.</strong><br>
        This item is found in the world — mining, mob drops, chest loot, trading or creative mode only.
      </div>`;
  }

  const used = [...(byIngredient.get(id) || [])].sort((a, b) => itemName(a).localeCompare(itemName(b)));
  if (used.length) {
    html += `<section class="station">
        <h3 class="station-title">${iconHTML('crafting_table')}Used to craft <span class="count">${used.length}</span></h3>
        <div class="usedin">${used.map((u) =>
          `<div class="cell" data-item="${esc(u)}" title="${esc(itemName(u))}">${iconHTML(u)}</div>`).join('')}</div>
      </section>`;
  }

  $('#detail-body').innerHTML = html;
  $('#detail-body').scrollTop = 0;
  $('#detail-crumb').textContent = state.history.slice(-3).map(itemName).join('  ›  ');
  $('#detail-back').disabled = state.history.length < 2;

  detail.hidden = false;
  backdrop.hidden = false;
  document.body.classList.add('modal-open');
  detail.style.animation = 'none';
  void detail.offsetWidth;
  detail.style.animation = '';
}

function closeDetail() {
  detail.hidden = true;
  backdrop.hidden = true;
  document.body.classList.remove('modal-open');
  state.history = [];
  if (location.hash) history.replaceState(null, '', location.pathname + location.search);
}

function goBack() {
  if (state.history.length < 2) return closeDetail();
  state.history.pop();
  openItem(state.history[state.history.length - 1], false);
  $('#detail-crumb').textContent = state.history.slice(-3).map(itemName).join('  ›  ');
  $('#detail-back').disabled = state.history.length < 2;
  history.replaceState(null, '', '#' + state.history[state.history.length - 1]);
}

/* ---------- cycling slots ---------------------------------------------- */

setInterval(() => {
  if (detail.hidden) return;
  for (const slot of detail.querySelectorAll('.slot[data-cycle]')) {
    const list = slot.dataset.cycle.split(',');
    const idx = (Number(slot.dataset.idx) + 1) % list.length;
    slot.dataset.idx = idx;
    slot.dataset.item = list[idx];
    slot.innerHTML = iconHTML(list[idx]);
  }
}, CYCLE_MS);

/* ---------- events ------------------------------------------------------ */

function wire() {
  // tabs
  const tabs = $('#tabs');
  const mkTab = (id, name, icon) => {
    const b = el('button', 'tab' + (id === state.category ? ' active' : ''));
    b.dataset.cat = id;
    b.innerHTML = `${icon ? iconHTML(icon, false) : ''}<span>${esc(name)}</span>`;
    return b;
  };
  tabs.appendChild(mkTab('all', 'All', 'crafting_table'));
  for (const c of DB.categories) tabs.appendChild(mkTab(c.id, c.name, c.icon));

  tabs.addEventListener('click', (e) => {
    const b = e.target.closest('.tab');
    if (!b) return;
    state.category = b.dataset.cat;
    tabs.querySelectorAll('.tab').forEach((t) => t.classList.toggle('active', t === b));
    b.scrollIntoView({ block: 'nearest', inline: 'center', behavior: 'smooth' });
    refresh();
  });

  // search
  let timer;
  const input = $('#search');
  input.addEventListener('input', () => {
    clearTimeout(timer);
    timer = setTimeout(() => {
      state.query = input.value;
      // a search always looks at the whole game, not just the open tab
      if (state.query.trim() && state.category !== 'all') {
        state.category = 'all';
        tabs.querySelectorAll('.tab').forEach((t) => t.classList.toggle('active', t.dataset.cat === 'all'));
      }
      refresh();
    }, 110);
  });

  $('#only-craftable').addEventListener('change', (e) => {
    state.craftableOnly = e.target.checked;
    refresh();
  });

  // grid interactions (delegated)
  gridEl.addEventListener('click', (e) => {
    const c = e.target.closest('.cell');
    if (c) { hideTip(); state.history = []; openItem(c.dataset.item); }
  });
  gridEl.addEventListener('keydown', (e) => {
    const c = e.target.closest('.cell');
    if (c && (e.key === 'Enter' || e.key === ' ')) { e.preventDefault(); state.history = []; openItem(c.dataset.item); }
  });
  gridEl.addEventListener('mouseover', (e) => {
    const c = e.target.closest('.cell');
    if (c) showTip(c.dataset.item, e.clientX, e.clientY);
  });
  gridEl.addEventListener('mousemove', (e) => { if (!tip.hidden) positionTip(e.clientX, e.clientY); });
  gridEl.addEventListener('mouseout', (e) => { if (!e.relatedTarget || !e.relatedTarget.closest('.cell')) hideTip(); });
  window.addEventListener('scroll', hideTip, { passive: true });

  // detail interactions
  detail.addEventListener('click', (e) => {
    const s = e.target.closest('[data-item]');
    if (s && s.dataset.item !== state.history[state.history.length - 1]) openItem(s.dataset.item);
  });
  $('#detail-close').addEventListener('click', closeDetail);
  $('#detail-back').addEventListener('click', goBack);
  backdrop.addEventListener('click', closeDetail);

  // keyboard
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') {
      if (!detail.hidden) closeDetail();
      else if (input.value) { input.value = ''; state.query = ''; refresh(); }
      return;
    }
    if (e.key === '/' && document.activeElement !== input) {
      e.preventDefault();
      input.focus();
      input.select();
    }
  });

  window.addEventListener('hashchange', () => {
    const id = decodeURIComponent(location.hash.slice(1));
    if (id && DB.items[id]) { state.history = []; openItem(id); }
    else if (!id) closeDetail();
  });
}

/* ---------- boot ---------------------------------------------------------- */

(async function boot() {
  gridEl.innerHTML = '<div class="loader" style="grid-column:1/-1">Loading every recipe <span>…</span></div>';
  try {
    const res = await fetch(DATA_URL);
    if (!res.ok) throw new Error(res.status + ' ' + res.statusText);
    DB = await res.json();
  } catch (err) {
    gridEl.innerHTML = `<div class="loader" style="grid-column:1/-1">Could not load the recipe data (${esc(err.message)}).</div>`;
    return;
  }

  buildIndexes();

  searchIndex = Object.keys(DB.items)
    .map((id) => ({ id, name: DB.items[id].n, lower: DB.items[id].n.toLowerCase() }))
    .sort((a, b) => a.name.localeCompare(b.name));

  $('#version-badge').textContent =
    `Minecraft ${DB.version.replace('-snapshot-', ' snapshot ')} · ${DB.recipes.length} recipes`;

  wire();
  refresh();

  const start = decodeURIComponent(location.hash.slice(1));
  if (start && DB.items[start]) openItem(start);
})();
